[build]
base = "client"
publish = "dist"
command = "npm install && npm run build"

[[redirects]]
from = "/api/v1/*"
to = "https://server.quickhire.store/api/v1/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200